services:
  otel-collector:
    image: ${REGISTRY:-}otel/opentelemetry-collector-contrib:${OTEL_COLLECTOR_VERSION:-latest}
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    restart: unless-stopped
    ports:
      - 4317:4317

  prometheus:
    image: ${REGISTRY:-}prom/prometheus:${PROMETHEUS_VERSION:-latest}
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100

  jaeger:
    image: ${REGISTRY:-}jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    restart: unless-stopped
    ports:
      - 16686:16686

  cadvisor:
    image: m.daocloud.io/gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    privileged: true
    user: "root"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /data/Docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    expose:
      - 8080
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: "root"
    ports:
     - '3001:3000'
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-data:/var/lib/grafana

  alert-webhook:
    image: registry.cn-beijing.aliyuncs.com/laiye-poc/grafana-alert-webhook:v0.1.3
    container_name: alert-webhook
    restart: unless-stopped
    ports:
     - '7999:8000'
    volumes:
      - ./conf/alert-webhook.toml:/home/works/program/conf/config.toml
      - ./alert-webhook-logs:/home/works/program/logs
