# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 30s
    static_configs:
      - targets: ['otel-collector:9090']
  - job_name: 'cAdvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.22.0.249:9100']
